############################################
##
##  capacity storage: 1Gi
##  /storage/data-mongodb-pv-0 must be created before
##
############################################
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-0
spec:
  storageClassName: mongodb-storage
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/storage/data-mongodb-pv-0"
